Make it possible for template to output imports
hexdigest/gowrap pull request #23
Opened 2020-05-05 09:16 UTC by recht

Sometimes, especially in large projects, goimports cannot properly resolve the imports by itself. This adds a helper function that can be used in templates, which outputs the imports from the original file as well as any additional imports required by the template itself.

I believe this also fixes #21.

2020-06-10 08:45 UTC, kop commented
I've tested this PR against #21 and can confirm that it solves the issue.

2020-06-11 15:13 UTC, kop commented on generator/generator.go
> +		allImports[i] = struct{}{}
```suggestion
		allImports[strings.TrimSpace(i)] = struct{}{}
```

2020-06-11 15:14 UTC, kop commented on generator/generator.go
> +		allImports[i] = struct{}{}
```suggestion
		allImports[strings.TrimSpace(i)] = struct{}{}
```

2020-06-17 15:17 UTC, hexdigest commented
Hi @recht,

Thank you for this wonderful PR! The only thing I want to ask is to provide a usage example by changing one of the templates within the templates dir.

@kop thank you for testing this!

2020-09-22 13:34 UTC, hexdigest requested changes

2020-09-22 13:34 UTC, hexdigest commented on generator/generator.go
> +		allImports[strings.TrimSpace(i)] = struct{}{}
@recht shouldn't we trim space from the user input first and then add quotes?
If you can fix this I'm ok to fix templates myself using this new helper.

2020-09-22 13:38 UTC, merged

2020-09-22 13:42 UTC, hexdigest commented
@recht jfyi I merged this PR to render_imports branch.
I'll fix some issues there and then it will be merged to master.

2020-09-22 14:17 UTC, hexdigest commented
@recht @kop 

Please check v1.1.10 the name of the helper is "Import"