toSnakeCase function
hexdigest/gowrap pull request #35
Opened 2021-03-16 09:24 UTC by dovbysh

2021-03-22 20:07 UTC, hexdigest requested changes

2021-03-22 20:07 UTC, hexdigest commented on cmd_generate.go
> +	"toSnakeCase": toSnakeCase,
@dovbysh Can you please change the key to "snake" just to make it more useful within a templates?

2021-04-02 04:16 UTC, AntonRutkevich commented on cmd_generate.go
> +	"toSnakeCase": toSnakeCase,
@dovbysh wow, I was just going to implement this same function) Could you please fix Max's comment and merge the PR?

2021-04-05 09:38 UTC, dovbysh commented on cmd_generate.go
> +	"toSnakeCase": toSnakeCase,
Да, конечно. Времени не хватало.

2021-04-05 17:12 UTC, merged

2021-04-05 18:03 UTC, hexdigest commented
@dovbysh Andrey, thanks for your contribution!
This functionality is available in v1.1.11

cc @AntonRutkevich

2021-04-07 04:07 UTC, AntonRutkevich commented
Thanks!